[2024-06-17T08:56:56.765+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.extract_load manual__2024-06-17T08:56:55.694666+00:00 [queued]>
[2024-06-17T08:56:56.775+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.extract_load manual__2024-06-17T08:56:55.694666+00:00 [queued]>
[2024-06-17T08:56:56.776+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-17T08:56:56.788+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_load> on 2024-06-17 08:56:55.694666+00:00
[2024-06-17T08:56:56.796+0000] {standard_task_runner.py:57} INFO - Started process 1488 to run task
[2024-06-17T08:56:56.799+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'extract_load', 'manual__2024-06-17T08:56:55.694666+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline_dag.py', '--cfg-path', '/tmp/tmpq0f7blgh']
[2024-06-17T08:56:56.801+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask extract_load
[2024-06-17T08:56:56.846+0000] {task_command.py:415} INFO - Running <TaskInstance: elt_pipeline.extract_load manual__2024-06-17T08:56:55.694666+00:00 [running]> on host 52e246c9d923
[2024-06-17T08:56:57.070+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@localhost.com' AIRFLOW_CTX_DAG_OWNER='t.nhatnguyen' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='extract_load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T08:56:55.694666+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T08:56:55.694666+00:00'
[2024-06-17T08:56:57.073+0000] {logging_mixin.py:151} INFO - {'endpoint': 'minio:9000', 'bucket_name': 'datalake_test', 'folder_name': 'test', 'access_key': 'minio_access_key', 'secret_key': 'minio_secret_key'}
[2024-06-17T08:56:57.075+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/elt_pipeline.py", line 55, in extract_load_to_datalake
    found = minio_client.bucket_exists(bucket_name=datalake_cfg["bucket_name"])
  File "/home/airflow/.local/lib/python3.8/site-packages/minio/api.py", line 696, in bucket_exists
    self._execute("HEAD", bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/minio/api.py", line 437, in _execute
    region = self._get_region(bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/minio/api.py", line 494, in _get_region
    response = self._url_open(
  File "/home/airflow/.local/lib/python3.8/site-packages/minio/api.py", line 423, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: InvalidBucketName, message: The specified bucket is not valid., resource: /datalake_test, request_id: 17D9BEE37C8F2156, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
[2024-06-17T08:56:57.084+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=elt_pipeline, task_id=extract_load, execution_date=20240617T085655, start_date=20240617T085656, end_date=20240617T085657
[2024-06-17T08:56:57.094+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task extract_load (S3 operation failed; code: InvalidBucketName, message: The specified bucket is not valid., resource: /datalake_test, request_id: 17D9BEE37C8F2156, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8; 1488)
[2024-06-17T08:56:57.131+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-17T08:56:57.154+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
