[2024-06-17T16:00:44.568+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.transform manual__2024-06-17T16:00:36.133936+00:00 [queued]>
[2024-06-17T16:00:44.582+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.transform manual__2024-06-17T16:00:36.133936+00:00 [queued]>
[2024-06-17T16:00:44.583+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-17T16:00:44.601+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform> on 2024-06-17 16:00:36.133936+00:00
[2024-06-17T16:00:44.609+0000] {standard_task_runner.py:57} INFO - Started process 170 to run task
[2024-06-17T16:00:44.613+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'transform', 'manual__2024-06-17T16:00:36.133936+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline_dag.py', '--cfg-path', '/tmp/tmp9nyf_1x6']
[2024-06-17T16:00:44.615+0000] {standard_task_runner.py:85} INFO - Job 101: Subtask transform
[2024-06-17T16:00:44.664+0000] {task_command.py:415} INFO - Running <TaskInstance: elt_pipeline.transform manual__2024-06-17T16:00:36.133936+00:00 [running]> on host c5bd232ea3a3
[2024-06-17T16:00:44.983+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@localhost.com' AIRFLOW_CTX_DAG_OWNER='t.nhatnguyen' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T16:00:36.133936+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T16:00:36.133936+00:00'
[2024-06-17T16:00:45.416+0000] {logging_mixin.py:151} INFO - {'endpoint': 'minio:9000', 'bucket_name': 'delta', 'folder_name': 'test', 'access_key': 'minio_access_key', 'secret_key': 'minio_secret_key'}
[2024-06-17T16:00:45.581+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/elt_pipeline.py", line 188, in transform_data
    s3_fs = s3fs.S3FileSystem(
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/spec.py", line 79, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3fs/core.py", line 187, in __init__
    self.s3 = self.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3fs/core.py", line 292, in connect
    self.s3 = self.session.create_client('s3', aws_access_key_id=self.key, aws_secret_access_key=self.secret, aws_session_token=self.token, config=conf, use_ssl=ssl,
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 159, in create_client
    client_args = self._get_client_args(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 490, in _get_client_args
    return args_creator.get_client_args(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/args.py", line 137, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: minio:9000
[2024-06-17T16:00:45.594+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=elt_pipeline, task_id=transform, execution_date=20240617T160036, start_date=20240617T160044, end_date=20240617T160045
[2024-06-17T16:00:45.613+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 101 for task transform (Invalid endpoint: minio:9000; 170)
[2024-06-17T16:00:45.673+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-17T16:00:45.695+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
