[2024-06-17T17:44:20.732+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.transform manual__2024-06-17T17:44:12.446965+00:00 [queued]>
[2024-06-17T17:44:20.740+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.transform manual__2024-06-17T17:44:12.446965+00:00 [queued]>
[2024-06-17T17:44:20.741+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-17T17:44:20.752+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform> on 2024-06-17 17:44:12.446965+00:00
[2024-06-17T17:44:20.760+0000] {standard_task_runner.py:57} INFO - Started process 842 to run task
[2024-06-17T17:44:20.766+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'transform', 'manual__2024-06-17T17:44:12.446965+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline_dag.py', '--cfg-path', '/tmp/tmpc_od_v3b']
[2024-06-17T17:44:20.772+0000] {standard_task_runner.py:85} INFO - Job 265: Subtask transform
[2024-06-17T17:44:20.868+0000] {task_command.py:415} INFO - Running <TaskInstance: elt_pipeline.transform manual__2024-06-17T17:44:12.446965+00:00 [running]> on host bf1afdb2f840
[2024-06-17T17:44:21.107+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@localhost.com' AIRFLOW_CTX_DAG_OWNER='t.nhatnguyen' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T17:44:12.446965+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T17:44:12.446965+00:00'
[2024-06-17T17:44:21.183+0000] {logging_mixin.py:151} INFO - {'endpoint': 'minio:9000', 'bucket_name': 'delta', 'folder_name': 'test', 'access_key': 'minio_access_key', 'secret_key': 'minio_secret_key'}
[2024-06-17T17:44:21.251+0000] {logging_mixin.py:151} INFO - Reading parquet file: /opt/***/data/2022/yellow_tripdata_2022-05.parquet
[2024-06-17T17:44:21.252+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/elt_pipeline.py", line 202, in transform_data
    df = pd.read_parquet(path)
UnboundLocalError: local variable 'path' referenced before assignment
[2024-06-17T17:44:21.263+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=elt_pipeline, task_id=transform, execution_date=20240617T174412, start_date=20240617T174420, end_date=20240617T174421
[2024-06-17T17:44:21.286+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 265 for task transform (local variable 'path' referenced before assignment; 842)
[2024-06-17T17:44:21.336+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-17T17:44:21.353+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
