[2024-06-16T17:34:48.825+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.extract_load manual__2024-06-16T17:34:47.474906+00:00 [queued]>
[2024-06-16T17:34:48.834+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.extract_load manual__2024-06-16T17:34:47.474906+00:00 [queued]>
[2024-06-16T17:34:48.835+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-16T17:34:48.847+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_load> on 2024-06-16 17:34:47.474906+00:00
[2024-06-16T17:34:48.854+0000] {standard_task_runner.py:57} INFO - Started process 897 to run task
[2024-06-16T17:34:48.857+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'extract_load', 'manual__2024-06-16T17:34:47.474906+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline_dag.py', '--cfg-path', '/tmp/tmphwxdyd7p']
[2024-06-16T17:34:48.859+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask extract_load
[2024-06-16T17:34:48.923+0000] {task_command.py:415} INFO - Running <TaskInstance: elt_pipeline.extract_load manual__2024-06-16T17:34:47.474906+00:00 [running]> on host 52e246c9d923
[2024-06-16T17:34:49.148+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@localhost.com' AIRFLOW_CTX_DAG_OWNER='t.nhatnguyen' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='extract_load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T17:34:47.474906+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T17:34:47.474906+00:00'
[2024-06-16T17:34:49.151+0000] {logging_mixin.py:151} INFO - while scanning a simple key
  in "/opt/***/config/datalake.yaml", line 9, column 1
could not find expected ':'
  in "/opt/***/config/datalake.yaml", line 9, column 119
[2024-06-16T17:34:49.151+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/elt_pipeline.py", line 41, in extract_load_to_datalake
    datalake_cfg = cfg["datalake"]
TypeError: 'NoneType' object is not subscriptable
[2024-06-16T17:34:49.159+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=elt_pipeline, task_id=extract_load, execution_date=20240616T173447, start_date=20240616T173448, end_date=20240616T173449
[2024-06-16T17:34:49.169+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task extract_load ('NoneType' object is not subscriptable; 897)
[2024-06-16T17:34:49.189+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-16T17:34:49.215+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
